# Generated by Django 5.2.1 on 2025-05-29 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('TRAVEL', 'Travel'), ('RENT', 'Rent'), ('BUSINESS', 'Business'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('EXPENSE_ADDED', 'New Expense Added'), ('PAYMENT_RECEIVED', 'Payment Received'), ('SETTLEMENT_REMINDER', 'Settlement Reminder'), ('GROUP_INVITE', 'Group Invitation'), ('PENDING_PAYMENT', 'Pending Payment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
