# Generated by Django 5.2.1 on 2025-05-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='start_date',
        ),
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('ONE_TIME', 'One-time'), ('RECURRING', 'Recurring')], default='ONE_TIME', max_length=20),
        ),
    ]
