# Generated by Django 5.2.1 on 2025-05-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='type',
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
