# Generated by Django 5.2.1 on 2025-05-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='frequency',
            field=models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=10, null=True),
        ),
    ]
