# Generated by Django 5.2.1 on 2025-05-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_expense_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_generated',
            field=models.BooleanField(default=False),
        ),
    ]
