# Generated by Django 5.2.1 on 2025-05-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_expense_is_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='custom_period_days',
            field=models.PositiveIntegerField(blank=True, help_text="Number of days for custom period (only used when tracking_period is 'CUSTOM')", null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='tracking_duration',
            field=models.PositiveIntegerField(default=1, help_text='How many periods ahead to track (e.g., 3 for 3 months)'),
        ),
        migrations.AddField(
            model_name='expense',
            name='tracking_period',
            field=models.CharField(choices=[('DAILY', 'Days'), ('WEEKLY', 'Weeks'), ('MONTHLY', 'Months'), ('CUSTOM', 'Custom Period (Days)')], default='MONTHLY', help_text='Unit for tracking duration', max_length=20),
        ),
    ]
