# Generated by Django 5.2.1 on 2025-05-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_expense_custom_period_days_expense_tracking_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='tracking_duration',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='How many periods ahead to track (e.g., 3 for 3 months)', null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='tracking_period',
            field=models.CharField(blank=True, choices=[('DAILY', 'Days'), ('WEEKLY', 'Weeks'), ('MONTHLY', 'Months'), ('CUSTOM', 'Custom Period (Days)')], default='MONTHLY', help_text='Unit for tracking duration', max_length=20, null=True),
        ),
    ]
