# Generated by Django 5.2.1 on 2025-05-29 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_expense_tracking_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='custom_period_days',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='tracking_duration',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='tracking_period',
        ),
    ]
